<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <a href ="https://gamers-zone.herokuapp.com/"><button id="redirecct">Go to Home</button></a>
    
    <!-- <script>
        document.querySelector('#redirect')
        .addEventListener('click', () => {
            window.location.href = 'https://gamers-zone.herokuapp.com/';
        });
        </script> -->

    <?php

    //  $apiKey = "YOUR_RAZORPAY_KEY";
    $apiKey = "rzp_test_svWXixrGqcIKe4";

    ?>

    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>



        <form action="http://www.example.com/payment/success/" method="POST">
        <script
            src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
            <!-- data-amount="<?php echo $_POST['amount'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35. -->
            data-amount= 2 * 100 ; // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
            data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
            data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
            data-buttontext="Pay with Razorpay"
            data-name="Traidev Solutions"
            data-description="Training & Development!"
            data-image="https://traidev.com/img/web-desgin-development.png"
            data-prefill.name="<?php echo $_POST['name'];?>"
            data-prefill.email="<?php echo $_POST['email'];?>"
            data-prefill.contact="<?php echo $_POST['mobile'];?>"
            // data-theme.color="#F37254"
            data-theme.color="1BA37F"

        ></script>

        <input type="hidden" custom="Hidden Element" name="hidden">
        </form>


</head>
<body>